### ISSUE TITLE
Final Objective & Requirements

### ISSUE THREAD

**Issue by sanmerkt** [sane120/animeTracker#2]
# Anime Tracker

### Search for Animes
A dedicated dynamic search bar where if you enter your anime in either japanese or english, the anime you search for pops up. Whenever you do not specify the name correctly, a recommendation list comes instead with all animes with that name in it.
 
### Watchlist
Whenever you click on an anime or the dedicated button on the list of animes, you are able to add them to the watchlist (maybe multiple lists aka, finished, on watch asf). This function will be the main point of this side as it allows you to track your animes. 

### Rate
Whenever you click on an anime or the dedicated button on the list of animes, you are able to rate these animes according your taste.

### Your current episode
Whenever you land up on your page, you will be able to define the current episode you are on. This will be also crucial as it helps you track your progress. 

### Login
Being able to have data backed up wherever you are, for that, a login is necessary. I will use Node.js with mySQL for that backend part. The usual Login contains the following points.
- username
- e-mail
- password

### Settings
The settings will be there to adjust following points.
- username
- e-mail
- password
- language
- avatar

Furthermore, you'll be able to chose a Light or Dark mode. That option will be nested on the Nav-Bar if you click on your username.

### View Charts
There are seasonal charts. They do work, as the name already suggests, with the four seasons, based on the Gregorian calendar. The application will show you the seasonal ratings & charts of the top titles from the past seasons and the current one.

### Receive notifications
Getting a notification whenever a new episode releases. Ideally I want to achieve it with an e-Mail system but am not sure yet, how to achieve that. But it will be an important point to have in this application.

### Backlog
Able to view your already watched movies like an history page. You'll be able to see which episode you've watched latest, for example.

**Comment by sanmerkt** [comment]
@FlorianHansPeterEsch

**Comment by hit-hapa** [comment]
try to be  more specific, e.g. Settings:

> Having a way to manage your userdata and preferences.

which userdata? -> name, email, password, profile picture, ...?
which preferences? -> color, animetype, language, ...?

**Comment by sane120** [comment]
> try to be more specific, e.g. Settings:
> 
> > Having a way to manage your userdata and preferences.
> 
> which userdata? -> name, email, password, profile picture, ...?
> which preferences? -> color, animetype, language, ...?

@hit-hapa 
I adjusted the whole document to specify more directly what I want to achieve.
