### ISSUE TITLE
Project Scope

### ISSUE THREAD

**Issue by sanmerkt** [sane120/animeTracker#4]
# Project Scope
### Nav Bar
- Used to visualize and control the whole application. Does have multiple choices such as "My List", "Search Bar", "Charts" and "Settings". More might follow. Rightmost will be a burger menu like dropdown for the Settings stuff.

### API fetch
- Gets all the API Data we do need to have a working application.
  - Titles
  - Genre
  - User Ratings
  - Release Dates
  - more might follow

### Tables with content
- Uses Vuetify component v-data-table.
- Uses the API's Data to get a Table with rows such as "Name", "Release Date", "Genre", "Studio", "Rating".

### Search
- Able to search for a specific title / name of a show. Dynamic adjustments / suggestions according to the users input.

### Notifications
- Handles all the notifications (preferably with an automated e-Mail sender).
  - Getting notifications for new episodes you haven't watched yet or / and new hyped releases.

### Login
- Visualizes the input fields to the user. 
- Provides a backlog for User Data data.

### User Data
- Gathers every information and preferences of users.

### Anime Overview
- Shows a brief description about the anime.

### Anime Watchlist
- Shows your watchlist with your current episode and the anime's current episode. It's a dropdown and editable to increase / decrease the counter.

### Cards
- Used to create content like Anime overview.
- Makes for an organized way to display content

### Chips
- Uses Vuetify component Chips
- Shows the "Tags" as Chips in the overview view of an anime.

### Dialogs
- Simple popup for multiple use-cases such as the anime overview on a list item.

### Footer
- Shows basic information like how to contact, About and FAQ.

### Tabs
- Useable with a List to create Tabs to categorize multiple lists.

### Menus
- Part of Nav Bar. Go to point Avatars for more.
- Burger like dropdown menu

### Settings Handler
- Gives you access to preferences such as Dark Mode, Language and User credentials.

### Avatars
- Predefined Profile Pictures.
- Showing up on the top right of the Nav Bar as your Profile and Settings Button. Same as in the usual Social Media sides.
- Availability to upload your own Avatar tbd.

### Switch
- Part of the Burger styled Menu "Settings / Avatar".
- Handles Dark / Light Mode

**Comment by FlorianHansPeterEsch** [comment]
Navbar provide to navigate to features like My list 
API data which data? animes, userdata,... 
Tables with content to show what (organized data(animes), provide sorting? )
Search -> Project scope is more like providing "something" for the User to Search
Notifications about what? (new episodes)
Login -> provides Backlog for -> User Data to remember watched animes, favorites,...  
Cards Dialogs Chips for visualizing "data" in "nice accessible" way (maybe another word) 
Settings Handler where user can manage there data or usersettings like
