### ISSUE TITLE
Resource Planning

### ISSUE THREAD

**Issue by sanmerkt** [sane120/animeTracker#5]
# Resource Planning
### Operating System
- Windows 10
  - Already installed on my work machine
- Windows 11
  - Already installed on my "home" machine 

### Code Editors
- Visual Studio Code
  - I am used to VS Code as it is the editor we work on in my team. It's already working with vue.js and typescript so why would I want to change.

### Languages
- Typescript
  - Typescript is the language we used in another project and to get more familiar with it, I did chose typescript for this project.

### Frameworks
- Vue.js
  - Vue.js is a modern JavaScript framework. I am already familiar with Vue from another project I worked with. That familiarity should get increased now.
- Vuetify
  - I am not too used to Vuetify, but the framework offers a lot of components to use. Am excited to work with it.
- Node.js
  - I am not really familiar with Node.js. I heard about it but never worked with it before. As it uses JavaScript code, I thought it's a nice thing to use Node.js on this project.

### Database
- mySQL
  - I already know mySQL back from my school days and SQL based databases are for me the only thing I do know for now.

### Source Control
- GitHub

### Project Plan
- GitHub Projects

**Comment by FlorianHansPeterEsch** [comment]
You could also add why you choose Windows 10 ... or why you want to use Typescript...

**Comment by Lyssa112** [comment]
@FlorianHansPeterEsch updated
