### ISSUE TITLE
Technical Design

### ISSUE THREAD

**Issue by sanmerkt** [sane120/animeTracker#6]
# List the components which will get used
### Options API vs Composition API
We'll use the Options API just cause of the fact that it's easier and more structured to use. For a small project like that, the benefits of the Composition API are not worthy.

### Vue Router
Using Routing. Makes for simple page handler.
### navigationBar
The first thing a user will probably see is the navigationBar. It will be a header with multiple options, including a search function. 

### searchBar
As previous mentioned in navigationBar, the searchBar will be integrated into the navigationBar. It'll make use of the Vuetify component to search for specific animes.

### contentTables
The skeleton for every display of tables.

### watchlistList
The watchlistList component will show us listings of animes from the users watchlist. The component contentTables will be of use.

### overviewList
Lists all sorts of animes with multiple sorting functions per column. The contentTables component will be of use.

### notificationHandler
Handles the notifications you get when a new episode got released.

### loginHandler
Handles the login procedure on the startup page.

**Comment by FlorianHansPeterEsch** [comment]
Focus on Frontend
1: Options oder Composition Api? and what is the advantage? example https://vuejs.org/examples/#simple-component  
2: using from vue Router?...
...

..: Components:
- "SerieList" to show series.
- "HeaderBar" navigate in application
...

3: Backend
will follow later
